spring.application.name=ecommerce-backend

# PostgreSQL Configuration (AWS RDS)
spring.datasource.url=jdbc:postgresql://ecommerce-platform.c5qq2iau4vsb.ap-southeast-2.rds.amazonaws.com:5432/postgres?currentSchema=ecommerce-platform
spring.datasource.username=postgres
spring.datasource.password=SWD392for10points
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=ecommerce-platform

# Frontend URL
app.frontend.base-url=http://localhost:5173


# pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema=ecommerce-platform
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# Google AI Gemini (API Key) - Chat only
spring.ai.google.genai.api-key=${GEMINI_API_KEY:AIzaSyDDtTUjR_6tM8O3rbBJ1RuX2Pble2cjLo4}
spring.ai.google.genai.transport=rest
spring.ai.google.genai.chat.options.model=gemma-3-27b-it
spring.ai.google.genai.chat.options.temperature=0.7

# Transformers Embedding Model (Local ONNX - all-MiniLM-L6-v2)
spring.ai.transformers.embedding.onnx.modelUri=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/onnx/model.onnx
spring.ai.transformers.embedding.tokenizer.uri=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer.json

ai.vector.threshold=0.7
ai.vector.top-k=5

# Server Configuration
server.port=8080

# JWT Configuration
jwt.secret=ecommerce-platform-secret-key-for-jwt-token-generation-must-be-256-bits-long
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000


# VNPay Configuration
payment.vnPay.url= https://sandbox.vnpayment.vn/paymentv2/vpcpay.html?
payment.vnPay.tmnCode=8HSQZKDY
payment.vnPay.secretKey=HFD4F9TWN7KZ875CRA0TU1FDQD1RUDV9
payment.vnPay.returnUrl=http://localhost:8080/api/payment/vn-pay-callback
payment.vnPay.version=2.1.0
payment.vnPay.command=pay
payment.vnPay.orderType=other


vnpt.ekyc.base-url=https://api.idg.vnpt.vn
vnpt.ekyc.token-id=4bdfb7b7-59f8-2ca9-e063-62199f0a1099
vnpt.ekyc.token-key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKrzd4MQa+FLBHnE7+f3bW/ELSqHbvoDbVVtG2E5oSAoEiRLUE2hBMQ8IIvt3KVNnNyq6PIsn7I6/rn33PztcYUCAwEAAQ==
vnpt.ekyc.access-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmFuc2FjdGlvbl9pZCI6IjVkOWUwNWNlLTY4ZWEtNDhkZC04MjVjLTg5MWEwZGY1MzEzZCIsInN1YiI6IjQwN2I4YWQ1LTE0ODUtMTFmMS1iNzBjLTU1MTU4NWEzNWJhNCIsImF1ZCI6WyJyZXN0c2VydmljZSJdLCJ1c2VyX25hbWUiOiJuZ3V5ZW50cnVuZ3RpbjEwMDMwNEBnbWFpbC5jb20iLCJzY29wZSI6WyJyZWFkIl0sImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0IiwibmFtZSI6Im5ndXllbnRydW5ndGluMTAwMzA0QGdtYWlsLmNvbSIsImV4cCI6MTc3MzI0MTY5OSwidXVpZF9hY2NvdW50IjoiNDA3YjhhZDUtMTQ4NS0xMWYxLWI3MGMtNTUxNTg1YTM1YmE0IiwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiIxZTVlNjYxYS0yMjNhLTRiY2ItOTNkMS0xZmYzZjA0OWY5ZDIiLCJjbGllbnRfaWQiOiJjbGllbnRhcHAifQ.HUSIK52qgcDfFdDdH3mogNRVCtl7m1y6fJRsd1orTeu-zg0Huh9Z5O7EG0aIft1r77m3fd8dTex8Z0udUmxHp4mqHTpJ0lOkTpLpzCva4ENqy0nlwalBMplYV_LvWqq5s5mymTYZUZLxQ-gb4t9ILFNrGrvMuDpHvrhkJl78zWeeZbD40qWujzB9efatuew00MO5rYvR86fRVvH1zsNK1iz7OatK8FupyI6KVQpP93cgfmYySWwAl5AuprMSm5MNwT895xbSttgW6-Ld3eXtrd0kP5wxArlBvg1dHoO4P5eh_VYa0aCouzoSqL3vLDwYvFERUiArstUfk2AHQqJTuA
vnpt.ekyc.mac-address=TEST1