spring.application.name=ecommerce-backend

# PostgreSQL Configuration (AWS RDS)


spring.datasource.url=jdbc:postgresql://ecommerce-platform.c5qq2iau4vsb.ap-southeast-2.rds.amazonaws.com:5432/postgres?currentSchema=ecommerce-platform
spring.datasource.username=postgres
spring.datasource.password=SWD392for10points
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=ecommerce-platform

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.schemas=ecommerce-platform
spring.flyway.default-schema=ecommerce-platform


# Frontend URL
app.frontend.base-url=http://localhost:5173


# pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema=ecommerce-platform
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# Google AI Gemini (API Key) - Chat only
spring.ai.google.genai.api-key=${GEMINI_API_KEY:AIzaSyCcOzzbf5FxmaZupHDT2PGMZ5NOtlP7Vpk}
spring.ai.google.genai.transport=rest
spring.ai.google.genai.chat.options.model=gemma-3-27b-it
spring.ai.google.genai.chat.options.temperature=0.7

# Transformers Embedding Model (Local ONNX - all-MiniLM-L6-v2)
spring.ai.transformers.embedding.onnx.modelUri=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/onnx/model.onnx
spring.ai.transformers.embedding.tokenizer.uri=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer.json

ai.vector.threshold=0.3
ai.vector.top-k=5

# Server Configuration
server.port=8080

# JWT Configuration
jwt.secret=ecommerce-platform-secret-key-for-jwt-token-generation-must-be-256-bits-long
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000


# VNPay Configuration
payment.vnPay.url= https://sandbox.vnpayment.vn/paymentv2/vpcpay.html?
payment.vnPay.tmnCode=8HSQZKDY
payment.vnPay.secretKey=HFD4F9TWN7KZ875CRA0TU1FDQD1RUDV9
payment.vnPay.returnUrl=http://localhost:8080/api/payment/vn-pay-callback
payment.vnPay.version=2.1.0
payment.vnPay.command=pay
payment.vnPay.orderType=other


vnpt.ekyc.base-url=https://api.idg.vnpt.vn
vnpt.ekyc.token-id=4cade226-f521-665a-e063-62199f0ab54f
vnpt.ekyc.token-key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKRXwWtoDHXDC2q/KYxSwRfh+M1orXF1Gx+4Sgxyg4GgzengdbRzYuoyIBBTj7iuXJnu1z3aloVRnciIK/RBb78CAwEAAQ==
vnpt.ekyc.access-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmFuc2FjdGlvbl9pZCI6Ijk2NjFjZjc4LWJmN2MtNGMyOC04YjE1LTdmZmMyOGFlYjU1MyIsInN1YiI6ImU2Mzk2NTY3LTFjOTItMTFmMS1hOWIwLWY3OGU1MDE3MDk2YyIsImF1ZCI6WyJyZXN0c2VydmljZSJdLCJ1c2VyX25hbWUiOiJ0aW5uZ3V5ZW4uMTAwOTA0QGdtYWlsLmNvbSIsInNjb3BlIjpbInJlYWQiXSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QiLCJuYW1lIjoidGlubmd1eWVuLjEwMDkwNEBnbWFpbC5jb20iLCJleHAiOjE3NzM4NTI3NjcsInV1aWRfYWNjb3VudCI6ImU2Mzk2NTY3LTFjOTItMTFmMS1hOWIwLWY3OGU1MDE3MDk2YyIsImF1dGhvcml0aWVzIjpbIlVTRVIiXSwianRpIjoiYzY2Yjg2Y2UtYjdhYi00M2MyLWE1M2ItNWIzMTVlODg5ZGMxIiwiY2xpZW50X2lkIjoiY2xpZW50YXBwIn0.uPixwb-fBm-r4lzT1fcdaEHjjelfpn31HCOFTYZNlzv_pKIzd_UG3HeGtd0U_RUB72S1XlQ20UPk_GZhocPvsBcVCKChTCfilblFd2facILkgEtpWpcj2vSju74SQNGjB_rPHOX2Ium5oNgQSOsE_l9x17Y5aZkpwIcnRJUbhLHICg3wG849hNVbbn-EgIjbSpcmBVvLWp21_LzBUzEnfl3zxiUC5rYhI9b9paZRG0Luwz4SxAdDJ24JddvYUV3XifE4sBkNlzALQf220N6AYUqKHXbHUpxZOZq0GVLx-ZMomqaPy3v4JhUxCYJdhTIouklvGW4F8RzBYAmbiimSnw
vnpt.ekyc.mac-address=TEST1