spring.application.name=ecommerce-backend

# PostgreSQL Configuration (AWS RDS)
spring.datasource.url=jdbc:postgresql://ecommerce-platform.c5qq2iau4vsb.ap-southeast-2.rds.amazonaws.com:5432/postgres?currentSchema=ecommerce-platform
spring.datasource.username=postgres
spring.datasource.password=SWD392for10points
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=ecommerce-platform

# Frontend URL
app.frontend.base-url=http://localhost:5173


# pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema=ecommerce-platform
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# Google AI Gemini (API Key) - Chat only
spring.ai.google.genai.api-key=${GEMINI_API_KEY:AIzaSyDHZSUybcDKUFIiKoJcVMii-5NTNPF43pg}
spring.ai.google.genai.transport=rest
spring.ai.google.genai.chat.options.model=gemma-3-27b-it
spring.ai.google.genai.chat.options.temperature=0.7

# Transformers Embedding Model (Local ONNX - all-MiniLM-L6-v2)
spring.ai.transformers.embedding.onnx.modelUri=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/onnx/model.onnx
spring.ai.transformers.embedding.tokenizer.uri=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer.json

ai.vector.threshold=0.3
ai.vector.top-k=5

# Server Configuration
server.port=8080

# JWT Configuration
jwt.secret=ecommerce-platform-secret-key-for-jwt-token-generation-must-be-256-bits-long
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000


# VNPay Configuration
payment.vnPay.url= https://sandbox.vnpayment.vn/paymentv2/vpcpay.html?
payment.vnPay.tmnCode=8HSQZKDY
payment.vnPay.secretKey=HFD4F9TWN7KZ875CRA0TU1FDQD1RUDV9
payment.vnPay.returnUrl=http://localhost:8080/api/payment/vn-pay-callback
payment.vnPay.version=2.1.0
payment.vnPay.command=pay
payment.vnPay.orderType=other


vnpt.ekyc.base-url=https://api.idg.vnpt.vn
vnpt.ekyc.token-id=4ce57ca2-53ec-754b-e063-63199f0a254a
vnpt.ekyc.token-key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIYs7KtNJCIkAnSHejsUQSvAeeGZZRPNMyPNfhZjSJVRzAjV+pOppjKAl//5MTuGWYR2N7C47COlCK1LRuoylf8CAwEAAQ==
vnpt.ekyc.access-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmFuc2FjdGlvbl9pZCI6IjE1ODg5NTA0LWM2MDgtNDQ1OS04YWQ4LTU4ZDE3ZjVhOWFhMCIsInN1YiI6ImYxYjY5NDA2LTFlYmUtMTFmMS05ZGUwLWU1YWYzMzMwMzA2MCIsImF1ZCI6WyJyZXN0c2VydmljZSJdLCJ1c2VyX25hbWUiOiJ0cmFucXVvY2NvbmcwNDAzMjAwMEBnbWFpbC5jb20iLCJzY29wZSI6WyJyZWFkIl0sImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0IiwibmFtZSI6InRyYW5xdW9jY29uZzA0MDMyMDAwQGdtYWlsLmNvbSIsImV4cCI6MTc3MzQ4MDU4MywidXVpZF9hY2NvdW50IjoiZjFiNjk0MDYtMWViZS0xMWYxLTlkZTAtZTVhZjMzMzAzMDYwIiwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiJhNzcxYTU5ZC04NWUyLTQwYjQtYTRiMi1iNGRmZTI4M2I5YmQiLCJjbGllbnRfaWQiOiJjbGllbnRhcHAifQ.b6NnFQeLmi4Wt9vmbCD--hHh1yv4EcVTJKbH95OznhWBjVArPF049U7qkG9OftESRIH0n-ctT1QyjNUPhpDEm9yVCHFx5hKjbnizO1qeNitPmZTDGZRuE8KNTVoS7lxJSPnM3VaHEoZm-y4eb9PNVBl6Crrk859gV1CTbLtcgKhhV49p8LVucXVp_1EUfCY9Y_Yjrs9QoWvymyvjTIogbPpCKU8s5y81sqpSL9LdEXYiAK0G4pynv-kPBInxC6ouqZr2Fn9UBk3xx0MHtubmbMCz4DSxULB-8b2BLD8K78US_5W_VeIuFXGgYSvkRFGfqcMjyqswYao8J0HghGMyfw
vnpt.ekyc.mac-address=TEST1